# Generated by Django 6.1 on 2026-08-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_has_seat_map'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=4)),
                ('number', models.PositiveIntegerField()),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to='ticketing.reservation')),
            ],
            options={
                'ordering': ['row_label', 'number'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='ticketing.seat'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('event', 'row_label', 'number'), name='unique_event_seat'),
        ),
    ]
