[project]
name = "backend"
version = "0.1.0"
description = "Plataforma de Eventos e Ingressos - API"
authors = [
    {name = "Matheus Duarte",email = "matheusduartenatal@gmail.com"}
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "django (>=6.1,<7.0)",
    "djangorestframework (>=3.18.0,<4.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "django-environ (>=0.14.0,<0.15.0)",
    "requests (>=2.34.2,<3.0.0)",
    "drf-spectacular (>=0.30.0,<0.31.0)",
    "drf-spectacular-sidecar (>=2026.8.1,<2027.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-django (>=4.14.0,<5.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py", "tests.py"]
addopts = "-ra"
