# Generated by Django 6.1 on 2026-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_seat_map',
            field=models.BooleanField(default=False),
        ),
    ]
