# Generated by Django 6.1 on 2026-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_has_seat_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_rating',
            field=models.CharField(blank=True, choices=[('L', 'Livre'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], default='', max_length=3),
        ),
    ]
